global:
  scrape_interval: 5s # Как часто забирать метрики (каждые 5 секунд)

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      # Указываем имя контейнера шлюза и его порт
      - targets: ['api-gateway:8080']